/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuadcopterSettings {
    maxThrottle: bigint;
    failsafeEnabled: boolean;
    thermalCameraEnabled: boolean;
    pidPitch: PIDSettings;
    pidYaw: PIDSettings;
    cameraEnabled: boolean;
    pidRoll: PIDSettings;
}
export interface PIDSettings {
    kd: number;
    ki: number;
    kp: number;
}
export interface backendInterface {
    getMaxThrottle(): Promise<bigint>;
    getPIDSettings(): Promise<{
        yaw: PIDSettings;
        roll: PIDSettings;
        pitch: PIDSettings;
    } | null>;
    getSettings(): Promise<QuadcopterSettings>;
    isCameraEnabled(): Promise<boolean>;
    isFailsafeEnabled(): Promise<boolean>;
    isThermalCameraEnabled(): Promise<boolean>;
    setSettings(pidRoll: PIDSettings, pidPitch: PIDSettings, pidYaw: PIDSettings, maxThrottle: bigint, cameraEnabled: boolean, thermalCameraEnabled: boolean, failsafeEnabled: boolean): Promise<void>;
}
import type { PIDSettings as _PIDSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMaxThrottle(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaxThrottle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaxThrottle();
            return result;
        }
    }
    async getPIDSettings(): Promise<{
        yaw: PIDSettings;
        roll: PIDSettings;
        pitch: PIDSettings;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPIDSettings();
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPIDSettings();
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSettings(): Promise<QuadcopterSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async isCameraEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCameraEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCameraEnabled();
            return result;
        }
    }
    async isFailsafeEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFailsafeEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFailsafeEnabled();
            return result;
        }
    }
    async isThermalCameraEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isThermalCameraEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isThermalCameraEnabled();
            return result;
        }
    }
    async setSettings(arg0: PIDSettings, arg1: PIDSettings, arg2: PIDSettings, arg3: bigint, arg4: boolean, arg5: boolean, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function from_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        yaw: _PIDSettings;
        roll: _PIDSettings;
        pitch: _PIDSettings;
    }]): {
    yaw: PIDSettings;
    roll: PIDSettings;
    pitch: PIDSettings;
} | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
