/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PIDSettings = IDL.Record({
  'kd' : IDL.Float64,
  'ki' : IDL.Float64,
  'kp' : IDL.Float64,
});
export const QuadcopterSettings = IDL.Record({
  'maxThrottle' : IDL.Nat,
  'failsafeEnabled' : IDL.Bool,
  'thermalCameraEnabled' : IDL.Bool,
  'pidPitch' : PIDSettings,
  'pidYaw' : PIDSettings,
  'cameraEnabled' : IDL.Bool,
  'pidRoll' : PIDSettings,
});

export const idlService = IDL.Service({
  'getMaxThrottle' : IDL.Func([], [IDL.Nat], ['query']),
  'getPIDSettings' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'yaw' : PIDSettings,
            'roll' : PIDSettings,
            'pitch' : PIDSettings,
          })
        ),
      ],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [QuadcopterSettings], ['query']),
  'isCameraEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isFailsafeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isThermalCameraEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'setSettings' : IDL.Func(
      [
        PIDSettings,
        PIDSettings,
        PIDSettings,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PIDSettings = IDL.Record({
    'kd' : IDL.Float64,
    'ki' : IDL.Float64,
    'kp' : IDL.Float64,
  });
  const QuadcopterSettings = IDL.Record({
    'maxThrottle' : IDL.Nat,
    'failsafeEnabled' : IDL.Bool,
    'thermalCameraEnabled' : IDL.Bool,
    'pidPitch' : PIDSettings,
    'pidYaw' : PIDSettings,
    'cameraEnabled' : IDL.Bool,
    'pidRoll' : PIDSettings,
  });
  
  return IDL.Service({
    'getMaxThrottle' : IDL.Func([], [IDL.Nat], ['query']),
    'getPIDSettings' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'yaw' : PIDSettings,
              'roll' : PIDSettings,
              'pitch' : PIDSettings,
            })
          ),
        ],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [QuadcopterSettings], ['query']),
    'isCameraEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isFailsafeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isThermalCameraEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'setSettings' : IDL.Func(
        [
          PIDSettings,
          PIDSettings,
          PIDSettings,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };