/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PIDSettings { 'kd' : number, 'ki' : number, 'kp' : number }
export interface QuadcopterSettings {
  'maxThrottle' : bigint,
  'failsafeEnabled' : boolean,
  'thermalCameraEnabled' : boolean,
  'pidPitch' : PIDSettings,
  'pidYaw' : PIDSettings,
  'cameraEnabled' : boolean,
  'pidRoll' : PIDSettings,
}
export interface _SERVICE {
  'getMaxThrottle' : ActorMethod<[], bigint>,
  'getPIDSettings' : ActorMethod<
    [],
    [] | [{ 'yaw' : PIDSettings, 'roll' : PIDSettings, 'pitch' : PIDSettings }]
  >,
  'getSettings' : ActorMethod<[], QuadcopterSettings>,
  'isCameraEnabled' : ActorMethod<[], boolean>,
  'isFailsafeEnabled' : ActorMethod<[], boolean>,
  'isThermalCameraEnabled' : ActorMethod<[], boolean>,
  'setSettings' : ActorMethod<
    [PIDSettings, PIDSettings, PIDSettings, bigint, boolean, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];